apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-daemonset
  namespace: volume1
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      name: test-daemonset
  template:
    metadata:
      labels:
        name: test-daemonset
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        command: ['sh', '-c', 'tail -f /var/log/syslog']
        volumeMounts:
        - name: varlog
          mountPath: /var/log/syslog
          readOnly: true
        securityContext:
          runAsUser: 0  # Запуск от имени root для гарантированного доступа
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/syslog
          type: File
